@extends('admin.layout')
@section('title','Student Progress Reports')
@section('content')
<div class="cards progress-summary"><div class="card blue"><small>Students in Report</small><strong>{{ count($students) }}</strong></div><div class="card green"><small>Average Progress</small><strong>{{ number_format($average,1) }}%</strong></div><div class="card purple"><small>Strong Performers</small><strong>{{ $highPerformers }}</strong></div><div class="card orange"><small>Need Support</small><strong>{{ $needsSupport }}</strong></div></div>
<section class="panel progress-panel"><form class="progress-filter" method="get"><input name="search" value="{{ request('search') }}" placeholder="Student, application or roll no..."><select name="course"><option value="">All Courses</option>@foreach($courses as $course)<option value="{{ $course->code }}" @selected(request('course')===$course->code)>{{ $course->code }}</option>@endforeach</select><select name="level"><option value="">All Performance</option><option value="high" @selected(request('level')==='high')>70% and above</option><option value="medium" @selected(request('level')==='medium')>40%–69%</option><option value="low" @selected(request('level')==='low')>Below 40%</option></select><button class="soft-btn">Search</button><a href="{{ route('admin.progress.index') }}">Clear</a></form>
@if(count($students))<div class="progress-records">@foreach($students as $student)@php($p=$student['progress'])<article>
<div class="overall-ring score-{{ $p['overall']>=70?'high':($p['overall']>=40?'medium':'low') }}"><strong>{{ number_format($p['overall'],0) }}%</strong><small>{{ $p['grade'] }}</small></div>
<div class="progress-student"><small>{{ $student['application_no'] }} · {{ $student['course_code'] }}</small><h3>{{ $student['student_name'] }}</h3><p>{{ $student['roll_no'] ?? 'Roll not assigned' }} · {{ $student['batch_name'] ?? $student['preferred_time'] ?? 'Batch not assigned' }}</p></div>
<div class="metric-chips"><span>Attendance <b>{{ $p['attendance_rate']===null?'—':$p['attendance_rate'].'%' }}</b></span><span>Assignments <b>{{ $p['assignment_average']===null?'—':$p['assignment_average'].'%' }}</b></span><span>Practice <b>{{ $p['practice_average']===null?'—':$p['practice_average'].'%' }}</b></span><span>Exams <b>{{ $p['exam_average']===null?'—':$p['exam_average'].'%' }}</b></span></div>
<div class="progress-fee"><small>Fee progress</small><b>{{ $p['fee_percentage'] }}%</b><span><i style="width:{{ $p['fee_percentage'] }}%"></i></span><em>Due ₹{{ number_format($p['balance_amount'],2) }}</em></div>
<a class="progress-print" href="{{ route('admin.progress.print',$student['id']) }}" target="_blank">Print Report</a>
</article>@endforeach</div>@else<div class="empty"><b>No student progress found</b><p>Adjust filters or admit students to generate reports.</p></div>@endif</section>
@endsection
