<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Student Portal · {{ $student['student_name'] }}</title><link rel="stylesheet" href="{{ asset('css/student-portal.css') }}"></head><body class="portal-body">
<header class="portal-header"><a class="portal-brand" href="{{ route('student.dashboard') }}"><img src="{{ asset('images/cnet-logo.webp') }}" alt="C-Net"><span><b>C-Net Student Portal</b><small>Computer Education</small></span></a><form method="post" action="{{ route('student.logout') }}">@csrf<button>Logout</button></form></header>
<main class="portal-shell"><section class="student-welcome"><div><small>WELCOME BACK</small><h1>{{ $student['student_name'] }}</h1><p>{{ $student['course_code'] }} — {{ $course?->title ?? 'Course' }}</p></div><div class="student-identity"><span>Application <b>{{ $student['application_no'] }}</b></span><span>Roll No. <b>{{ $student['roll_no'] ?? 'Not assigned' }}</b></span><span>Batch <b>{{ $student['batch_name'] ?? $student['preferred_time'] ?? 'Not assigned' }}</b></span></div></section>
<nav class="portal-nav"><a href="#fees">Fees</a><a href="#attendance">Attendance</a><a href="#learning">Study Materials</a><a href="#results">Results</a><a href="#certificates">Certificates</a></nav>
<section class="portal-stats"><article><small>Course Fee</small><strong>₹{{ number_format($student['course_fee'],2) }}</strong></article><article><small>Total Paid</small><strong>₹{{ number_format($student['paid_amount'],2) }}</strong></article><article><small>Balance Due</small><strong class="{{ $student['balance_amount']>0?'warning':'success' }}">₹{{ number_format($student['balance_amount'],2) }}</strong></article><article><small>Attendance</small><strong>{{ number_format($attendanceRate,1) }}%</strong></article></section>
<section class="portal-panel" id="fees"><div class="portal-title"><div><small>FEE ACCOUNT</small><h2>Payment History</h2></div><span class="portal-status status-{{ $student['payment_status'] }}">{{ ucfirst($student['payment_status']) }}</span></div>
@if(count($student['payments']))<div class="portal-table-wrap"><table><thead><tr><th>Date</th><th>Receipt</th><th>Mode</th><th>Reference</th><th>Amount</th></tr></thead><tbody>@foreach($student['payments'] as $payment)<tr><td>{{ \Carbon\Carbon::parse($payment['payment_date'])->format('d M Y') }}</td><td>{{ $payment['receipt_no'] }}</td><td>{{ strtoupper($payment['mode']) }}</td><td>{{ $payment['reference'] ?: '—' }}</td><td><b>₹{{ number_format($payment['amount'],2) }}</b></td></tr>@endforeach</tbody></table></div>@elseif($student['paid_amount']>0)<p class="portal-empty">Opening paid amount: ₹{{ number_format($student['paid_amount'],2) }}. Future transactions will appear here.</p>@else<p class="portal-empty">No fee payment recorded yet.</p>@endif</section>
<section class="portal-panel" id="attendance"><div class="portal-title"><div><small>ATTENDANCE</small><h2>Your Attendance</h2></div><div class="attendance-chips"><span class="present">Present {{ $attendanceCounts['present'] ?? 0 }}</span><span class="absent">Absent {{ $attendanceCounts['absent'] ?? 0 }}</span><span class="leave">Leave {{ $attendanceCounts['leave'] ?? 0 }}</span></div></div>
@if(count($attendance))<div class="attendance-calendar">@foreach(array_slice($attendance,0,31) as $row)<div class="{{ $row['status'] }}"><b>{{ \Carbon\Carbon::parse($row['date'])->format('d') }}</b><small>{{ \Carbon\Carbon::parse($row['date'])->format('M') }}</small><span>{{ ucfirst($row['status']) }}</span></div>@endforeach</div>@else<p class="portal-empty">Attendance records are not available yet.</p>@endif</section>
<section class="portal-panel" id="learning"><div class="portal-title"><div><small>COURSE RESOURCES</small><h2>Study Materials & Assignments</h2></div><span class="portal-status status-paid">{{ count($learningResources) }} available</span></div>
@if(count($learningResources))<div class="learning-portal-grid">@foreach($learningResources as $resource)<article class="portal-resource type-{{ $resource['type'] }}">
<div class="portal-resource-icon">{{ $resource['is_pinned'] ? '★' : ($resource['type']==='video' ? '▶' : ($resource['type']==='assignment' ? '✓' : '▰')) }}</div>
<div><div class="portal-resource-meta"><span>{{ strtoupper($resource['type']) }}</span>@if($resource['is_pinned'])<b>PINNED</b>@endif @if($resource['due_date'])<strong>Due {{ \Carbon\Carbon::parse($resource['due_date'])->format('d M Y') }}</strong>@endif</div><h3>{{ $resource['title'] }}</h3><p>{{ $resource['description'] ?: 'Open the resource to continue learning.' }}</p></div>
<a href="{{ $resource['link_url'] }}" target="_blank" rel="noopener noreferrer">Open Resource ↗</a>
</article>@endforeach</div>@else<p class="portal-empty">No study material has been published for your course yet.</p>@endif</section>
<section class="portal-panel" id="results"><div class="portal-title"><div><small>ACADEMIC RESULTS</small><h2>Exams & Marksheets</h2></div></div>
@if(count($results))<div class="result-portal-grid">@foreach($results as $result)<article><div class="result-percent {{ $result['result_status'] }}"><strong>{{ number_format($result['percentage'],1) }}%</strong><small>Grade {{ $result['grade'] }}</small></div><div><h3>{{ $result['exam_name'] }}</h3><p>{{ \Carbon\Carbon::parse($result['exam_date'])->format('d M Y') }} · {{ strtoupper($result['result_status']) }}</p><small>{{ $result['result_no'] }}</small></div><a href="{{ route('student.results.marksheet',$result['id']) }}" target="_blank">View Marksheet</a></article>@endforeach</div>@else<p class="portal-empty">No examination result has been published yet.</p>@endif</section>
<section class="portal-panel" id="certificates"><div class="portal-title"><div><small>ACHIEVEMENTS</small><h2>Your Certificates</h2></div></div>
@if(count($certificates))<div class="certificate-portal-grid">@foreach($certificates as $certificate)<article><div class="cert-symbol">◇</div><div><h3>{{ $certificate['title'] }}</h3><p>{{ ucwords($certificate['type']) }} · {{ \Carbon\Carbon::parse($certificate['issue_date'])->format('d M Y') }}</p><small>{{ $certificate['verification_code'] }}</small></div><div><a href="{{ route('student.certificates.print',$certificate['id']) }}" target="_blank">Print</a><a href="{{ route('certificates.verify',['code'=>$certificate['verification_code']]) }}" target="_blank">Verify</a></div></article>@endforeach</div>@else<p class="portal-empty">No certificate has been issued yet.</p>@endif</section>
<footer class="portal-footer">C-Net Computer Education · Student records are private and session-protected.</footer></main></body></html>
