@extends('admin.layout')
@section('title','Online Practice Tests')
@section('content')
@if($starterCount>0)<div class="starter-installed"><b>{{ $starterCount }} ready-made course assessment sets installed automatically.</b><span>हर course में 2 Practice, 2 Terminal और 1 Final test रहेगा। आप इन्हें Hide या Delete कर सकते हैं।</span></div>@endif
<div class="cards practice-summary"><div class="card blue"><small>Total Tests</small><strong>{{ count($tests) }}</strong></div><div class="card green"><small>Active Tests</small><strong>{{ $activeCount }}</strong></div><div class="card orange"><small>Total Attempts</small><strong>{{ $attemptCount }}</strong></div><div class="card purple"><small>Courses</small><strong>{{ $courses->count() }}</strong></div></div>
<div class="practice-admin-grid">
<section class="panel practice-entry"><div class="panel-title"><div><small>CREATE MCQ TEST</small><h2>Course-wise online test</h2></div></div>
<form method="post" action="{{ route('admin.practice.store') }}">@csrf
<div class="form-grid"><label>Course<select name="course_code" required><option value="">Select course</option>@foreach($courses as $course)<option value="{{ $course->code }}" @selected(old('course_code')===$course->code)>{{ $course->code }} — {{ $course->title }}</option>@endforeach</select></label><label>Test Title<input name="title" value="{{ old('title') }}" maxlength="180" required></label><label>Assessment Type<select name="assessment_type" required><option value="practice">Practice Test</option><option value="terminal">Terminal Test</option><option value="final">Final Test</option></select></label><label>Sequence (1–5)<input type="number" name="assessment_order" value="{{ old('assessment_order',1) }}" min="1" max="5" required></label><label>Result Weight %<input type="number" name="assessment_weight" value="{{ old('assessment_weight',20) }}" min="1" max="100" required></label><label>Duration (minutes)<input type="number" name="duration_minutes" value="{{ old('duration_minutes',20) }}" min="1" max="180" required></label><label>Pass Percentage<input type="number" name="pass_percentage" value="{{ old('pass_percentage',40) }}" min="1" max="100" required></label></div>
<div class="question-builder">@for($i=0;$i<5;$i++)<fieldset><legend>Question {{ $i+1 }} {{ $i===0?'(required)':'(optional)' }}</legend><input name="questions[{{ $i }}][prompt]" value="{{ old('questions.'.$i.'.prompt') }}" placeholder="Type question..." {{ $i===0?'required':'' }}><div><input name="questions[{{ $i }}][option_a]" value="{{ old('questions.'.$i.'.option_a') }}" placeholder="Option A"><input name="questions[{{ $i }}][option_b]" value="{{ old('questions.'.$i.'.option_b') }}" placeholder="Option B"><input name="questions[{{ $i }}][option_c]" value="{{ old('questions.'.$i.'.option_c') }}" placeholder="Option C"><input name="questions[{{ $i }}][option_d]" value="{{ old('questions.'.$i.'.option_d') }}" placeholder="Option D"></div><label>Correct Answer<select name="questions[{{ $i }}][correct]"><option value="A">A</option><option value="B">B</option><option value="C">C</option><option value="D">D</option></select></label></fieldset>@endfor</div>
<button class="btn">Publish Practice Test</button></form></section>
<section class="panel practice-list-panel"><form class="practice-filter" method="get"><input name="search" value="{{ request('search') }}" placeholder="Search test or course..."><select name="course"><option value="">All Courses</option>@foreach($courses as $course)<option value="{{ $course->code }}" @selected(request('course')===$course->code)>{{ $course->code }}</option>@endforeach</select><button class="soft-btn">Search</button><a href="{{ route('admin.practice.index') }}">Clear</a></form>
@if(count($tests))<div class="practice-records">@foreach($tests as $test)<article class="{{ ($test['is_active']??true)?'':'test-hidden' }}"><div class="test-score"><strong>{{ count($test['questions']) }}</strong><small>Questions</small></div><div><small>{{ $test['course_code'] }} · {{ ucfirst($test['assessment_type']??'practice') }} · {{ $test['duration_minutes'] }} minutes @if(isset($test['starter_key'])) · READY-MADE SET @endif</small><h3>{{ $test['title'] }}</h3><p>Pass: {{ $test['pass_percentage'] }}% · Weight: {{ $test['assessment_weight']??0 }}% · Attempts: {{ count($test['attempts']) }}</p></div><div class="practice-actions"><form method="post" action="{{ route('admin.practice.toggle',$test['id']) }}">@csrf @method('PATCH')<button>{{ ($test['is_active']??true)?'Hide':'Show' }}</button></form><form method="post" action="{{ route('admin.practice.destroy',$test['id']) }}" onsubmit="return confirm('Delete test and all attempts?')">@csrf @method('DELETE')<button class="danger">Delete</button></form></div></article>@endforeach</div>@else<div class="empty"><b>No practice tests found</b><p>Create the first MCQ test using the form.</p></div>@endif
@if(count($attempts))<div class="recent-attempts"><h3>Recent Student Attempts</h3><div class="portal-table-wrap"><table><thead><tr><th>Student</th><th>Course</th><th>Score</th><th>Status</th><th>Date</th></tr></thead><tbody>@foreach($attempts as $attempt)<tr><td>{{ $attempt['student']['student_name'] ?? 'Student' }}</td><td>{{ $attempt['course_code'] }}</td><td>{{ $attempt['correct_answers'] }}/{{ $attempt['total_questions'] }} ({{ number_format($attempt['percentage'],1) }}%)</td><td>{{ strtoupper($attempt['status']) }}</td><td>{{ \Carbon\Carbon::parse($attempt['submitted_at'])->format('d M Y') }}</td></tr>@endforeach</tbody></table></div></div>@endif
</section></div>
@endsection
